#! /bin/sh

feh --bg-scale ~/wallpaper/current &
polybar_launch=~/.config/polybar/launch.sh
[ -x $polybar_launch ] && $polybar_launch
dunst &
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config click_to_focus	any
bspc config split_ratio 0.6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color #38032c
bspc config focused_border_color #e80cb5
bspc config pointer_modifier control
bspc config pointer_action2 resize
bspc config pointer_action1 move
bspc rule -a *:irssi desktop=^4
bspc rule -a *:vimpc desktop=^10 state=floating
